---
title: "An analysis on the influences between programming languages"
author: Eros Fabrici
date: 05/02/21
output: ioslides_presentation
---

## Influence

Type any R code in the chunk and check the result:

```{r, echo = FALSE}
source('clean_data.R')
library(tidyverse)
library(igraph)
library(ggraph)
library(tidygraph)

graph <- tbl_graph(nodes = programming_languages_tibble,
                   edges = influences_tibble, directed = TRUE)
```
```{r, echo = FALSE}
get_centrality <- function (graph, centrality_function) {
  result_centraility <-
          graph %>%
          activate(nodes) %>%
          mutate(influence = centrality_function)
  return(result_centraility)
}

plot_centrality <- function (graph_with_centrality, filtering_degree = 0) {
  graph_with_centrality %>%
          filter(influence > filtering_degree) %>%
          filter(!node_is_isolated()) %>%
          ggraph(layout = 'fr') +
          geom_edge_link(aes(alpha = stat(index)), show.legend = FALSE, edge_colour = 'grey66') +
          geom_node_point(aes(size = influence), show.legend = FALSE) +
          geom_node_text(aes(label = name), repel = TRUE, show.legend = FALSE, colour = 'red', family = 'serif') +
          theme_void()
}

plot_most_influent_languages <- function (graph_with_centraility, how_many = 10, centrality_metric) {
  as_data_frame(graph_with_centraility, what = 'vertices') %>%
          top_n(how_many) %>%
          select(name, influence) %>%
          ggplot(aes(x = reorder(as.factor(name), -influence), y = influence)) +
          geom_bar(stat = 'identity', fill = 'blue4') +
          labs(
                  title = 'Top ten most influential programming languages',
                  subtitle = paste('Centrality metric used:', centrality_metric),
                  x = '',
                  y = 'Influence'
          ) +
          theme_classic()
}

subgraph_of_programming_language <- function (graph, programming_language,
                                              selected_mode = 'all') {
  subgraph <- graph %>%
          convert(to_bfs_tree,
                  which(.N()$name == programming_language), mode = selected_mode) %>%
          activate(nodes) %>%
          filter(!node_is_isolated())

  subgraph %>%
          ggraph(layout = 'fr') +
          geom_edge_link(aes(alpha = stat(index)), show.legend = FALSE, edge_colour = 'grey66') +
          geom_node_point(aes(size = influence), show.legend = FALSE) +
          geom_node_text(aes(filter = name != programming_language, label = name),
                         repel = TRUE, show.legend = FALSE, colour = 'red', family = 'serif') +
          geom_node_text(aes(filter = name == programming_language, label = name),
                         colour = 'green', family = 'serif', repel = TRUE, show.legend = FALSE) +
          theme_void()
}
```

```{r}
graph_influence_degree <- get_centrality(graph, centrality_degree(mode = 'in'))
plot_centrality(graph_influence_degree)
plot_most_influent_languages(graph_influence_degree, centrality_metric = 'in-degree')
```

```{r}
graph_influence_degree <- get_centrality(graph, centrality_degree(mode = 'out'))
plot_centrality(graph_influence_degree)
plot_most_influent_languages(graph_influence_degree, centrality_metric = 'out-degree')
```
```{r}
graph_closeness_centrality <- get_centrality(graph, centrality_closeness(mode = 'in'))
plot_centrality(graph_closeness_centrality)
plot_most_influent_languages(graph_closeness_centrality, centrality_metric = 'closeness')
```
```{r}
graph_edge_betweenness <- get_centrality(graph, centrality_betweenness())
plot_centrality(graph_edge_betweenness)
plot_most_influent_languages(graph_edge_betweenness, centrality_metric = 'betweenness')
```
```{r}
subgraph_of_programming_language(graph_edge_betweenness, 'python', 'out')
subgraph_of_programming_language(graph_edge_betweenness, 'ruby')
subgraph_of_programming_language(graph_edge_betweenness, 'haskell', 'out')
subgraph_of_programming_language(graph_edge_betweenness, 'c')
```
```{r}
selected_mode <- 'out'
subgraph_of_programming_language(graph_edge_betweenness, 'python', selected_mode)
subgraph_of_programming_language(graph_edge_betweenness, 'ruby', selected_mode)
subgraph_of_programming_language(graph_edge_betweenness, 'haskell', selected_mode)
subgraph_of_programming_language(graph_edge_betweenness, 'c', selected_mode)
```
```{r}
graph_authority <- get_centrality(graph, centrality_authority())
plot_centrality(graph_authority)
plot_most_influent_languages(graph_authority, centrality_metric = 'authority')
```
```{r}
graph_hub <- get_centrality(graph, centrality_hub())
plot_centrality(graph_hub)
plot_most_influent_languages(graph_hub, centrality_metric = 'hub')
```
```{r}
graph_pagerank <- get_centrality(graph, centrality_pagerank())
plot_centrality(graph_pagerank)
plot_most_influent_languages(graph_pagerank, centrality_metric = 'pagerank')
```
# Clustering
I linguaggi dello stesso paradigma si influenzano pricipalmente tra di loro?
```{r}
graph %>%
        get_centrality(centrality_function = centrality_degree(mode = 'in')) %>%
        subgraph_of_programming_language(programming_language = 'java', selected_mode = 'out')
```
```{r}
graph_no_isolated_nodes <- graph %>% activate(nodes) %>% filter(!node_is_isolated())
clusters <- cluster_infomap(graph_no_isolated_nodes, modularity = FALSE)
plot(clusters, graph_no_isolated_nodes, layout = layout_with_fr(graph_no_isolated_nodes))
```


## Third slide

Now, click the **Run** button on the chunk toolbar to [execute](https://www.jetbrains.com/help/pycharm/r-markdown.html#run-r-code) the chunk code. The result should be placed under the chunk.
Click the **Knit and Open Document** to built and preview an output.